import unittest
import os
import tempfile
from docx_mcp_server.server import (
    docx_create,
    docx_save,
    docx_close,
    docx_add_heading,
    docx_add_paragraph,
    docx_add_run,
    docx_set_font,
    docx_add_table,
    docx_get_cell,
    docx_add_paragraph_to_cell,
    session_manager
)

class TestEndToEnd(unittest.TestCase):
    def test_full_document_creation(self):
        # 1. Start Session
        session_id = docx_create()
        self.assertIsNotNone(session_id)

        # 2. Add Title
        title_id = docx_add_heading(session_id, "Monthly Report", level=0)
        self.assertTrue(title_id.startswith("para_"))

        # 3. Add Intro Paragraph
        para_id = docx_add_paragraph(session_id, "This is an automated report generated by ")
        run_id = docx_add_run(session_id, para_id, "Claude")

        # 4. Style the "Claude" run
        docx_set_font(session_id, run_id, bold=True, color_hex="0000FF")

        # 5. Add a Data Table
        docx_add_heading(session_id, "Data Summary", level=1)
        table_id = docx_add_table(session_id, rows=2, cols=2)

        # Header Row
        c00 = docx_get_cell(session_id, table_id, 0, 0)
        docx_add_paragraph_to_cell(session_id, c00, "Metric")

        c01 = docx_get_cell(session_id, table_id, 0, 1)
        docx_add_paragraph_to_cell(session_id, c01, "Value")

        # Data Row
        c10 = docx_get_cell(session_id, table_id, 1, 0)
        docx_add_paragraph_to_cell(session_id, c10, "Revenue")

        c11 = docx_get_cell(session_id, table_id, 1, 1)
        docx_add_paragraph_to_cell(session_id, c11, "$1,000,000")

        # 6. Save
        with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
            output_path = tmp.name

        try:
            result = docx_save(session_id, output_path)
            self.assertIn("saved successfully", result)

            # Verify file exists and has size
            self.assertTrue(os.path.exists(output_path))
            self.assertGreater(os.path.getsize(output_path), 0)

        finally:
            if os.path.exists(output_path):
                os.remove(output_path)
            docx_close(session_id)

if __name__ == '__main__':
    unittest.main()
