import unittest
import os
import json
import tempfile
from tests.helpers import extract_session_id, extract_element_id

from docx_mcp_server.server import (
    docx_create,
    docx_save,
    docx_close,
    docx_insert_heading,
    docx_insert_paragraph,
    docx_insert_run,
    docx_set_font,
    docx_insert_table,
    docx_get_cell,
    docx_insert_paragraph_to_cell,
    session_manager
)

def _extract(response):
    eid = extract_element_id(response)
    if not eid:
         # Fallback for checking success if no element_id expected
         if "✅ Success" not in response and "status" not in response:
             raise ValueError(f"Tool failed: {response}")
    return {"element_id": eid}

class TestEndToEnd(unittest.TestCase):
    def test_full_document_creation(self):
        # 1. Start Session
        session_response = docx_create()

        session_id = extract_session_id(session_response)
        self.assertIsNotNone(session_id)

        # 2. Add Title
        title_resp = docx_insert_heading(session_id, "Monthly Report", position="end:document_body", level=0)
        title_id = _extract(title_resp)["element_id"]
        self.assertTrue(title_id.startswith("para_"))

        # 3. Add Intro Paragraph
        para_resp = docx_insert_paragraph(session_id, "This is an automated report generated by ", position="end:document_body")
        para_id = _extract(para_resp)["element_id"]
        run_resp = docx_insert_run(session_id, "Claude", position=f"inside:{para_id}")
        run_id = _extract(run_resp)["element_id"]

        # 4. Style the "Claude" run
        docx_set_font(session_id, run_id, bold=True, color_hex="0000FF")

        # 5. Add a Data Table
        docx_insert_heading(session_id, "Data Summary", position="end:document_body", level=1)
        table_resp = docx_insert_table(session_id, rows=2, cols=2, position="end:document_body")
        table_id = _extract(table_resp)["element_id"]

        # Header Row
        c00_resp = docx_get_cell(session_id, table_id, 0, 0)
        c00 = _extract(c00_resp)["element_id"]
        docx_insert_paragraph_to_cell(session_id, "Metric", position=f"inside:{c00}")

        c01_resp = docx_get_cell(session_id, table_id, 0, 1)
        c01 = _extract(c01_resp)["element_id"]
        docx_insert_paragraph_to_cell(session_id, "Value", position=f"inside:{c01}")

        # Data Row
        c10_resp = docx_get_cell(session_id, table_id, 1, 0)
        c10 = _extract(c10_resp)["element_id"]
        docx_insert_paragraph_to_cell(session_id, "Revenue", position=f"inside:{c10}")

        c11_resp = docx_get_cell(session_id, table_id, 1, 1)
        c11 = _extract(c11_resp)["element_id"]
        docx_insert_paragraph_to_cell(session_id, "$1,000,000", position=f"inside:{c11}")

        # 6. Save
        with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
            output_path = tmp.name

        try:
            result = docx_save(session_id, output_path)
            # Check for success in Markdown response
            from tests.helpers import is_success
            self.assertTrue(is_success(result), f"Save failed: {result}")

            # Verify file exists and has size
            self.assertTrue(os.path.exists(output_path))
            self.assertGreater(os.path.getsize(output_path), 0)

        finally:
            if os.path.exists(output_path):
                os.remove(output_path)
            docx_close(session_id)

if __name__ == '__main__':
    unittest.main()
